version: '3'

includes:
  shared:
    taskfile: ../SharedTaskfile.yml
    dir: ./

tasks:
  check:
    cmds:
      - task: shared:check

  test:
    cmds:
      - task: shared:test

  lint:
    cmds:
      - task: shared:lint

  "lint:fix":
    cmds:
      - task: shared:lint:fix

  format:
    cmds:
      - task: shared:format

  "gen:css":
    env:
      NODE_ENV: production
    sources:
      - ./src/**/*.rs
      - ./index.html
      - ./src/**/*.html
      - ./src/**/*.css
    cmds:
      - tailwindcss -c ./tailwind.config.js -o ./tailwind.css --minify

  "gen:css:watch":
    cmds:
      - task --watch "gen:css"

  serve:
    cmds:
      - trunk serve --port 8089
