version: '3'

includes:
  server:
    taskfile: ./server/Taskfile.yml
    dir: ./server
  client:
    taskfile: ./client/Taskfile.yml
    dir: ./client

tasks:
  init:
    cmds:
      - rustup target add wasm32-unknown-unknown
      - ./scripts/k6-install.sh
      - npm install -g tailwindcss concurrently
      - mkcert -install

  start:
    deps:
      - task: client:gen:css:watch
      - task: start:docker

  "start:docker":
    cmds:
      - docker-compose down && docker-compose up

  certs:
    cmds:
      - mkcert -cert-file certs/local-cert.pem -key-file certs/local-key.pem "todo.localhost" "*.todo.localhost"

