version: '3'

env:
  MIGRATION_DIR: ./migration
  K6_INSECURE_SKIP_TLS_VERIFY: true
  K6_DIR: ./k6

includes:
  shared:
    taskfile: ../SharedTaskfile.yml
    dir: ./
  crud:
    taskfile: ../SharedTaskfile.yml
    dir: ./crud
  entity:
    taskfile: ../SharedTaskfile.yml
    dir: ./entity
  migration:
    taskfile: ../SharedTaskfile.yml
    dir: ./migration

tasks:
  check:
    cmds:
      - task: shared:check
      - task: crud:check
      - task: entity:check
      - task: migration:check

  test:
    cmds:
      - task: shared:test
      - task: crud:test
      - task: entity:test
      - task: migration:test

  lint:
    cmds:
      - task: shared:lint
      - task: crud:lint
      - task: entity:lint
      - task: migration:lint

  "lint:fix":
    cmds:
      - task: shared:lint:fix
      - task: crud:lint:fix
      - task: entity:lint:fix
      - task: migration:lint:fix

  format:
    cmds:
      - task: shared:format
      - task: crud:format
      - task: entity:format
      - task: migration:format

  "mig:init":
    cmds:
      - docker-compose exec api sea-orm-cli migrate init -d ${MIGRATION_DIR}

  "mig:create":
    cmds:
      - echo "todo"

  "mig:run":
    cmds:
      - docker-compose exec api sea-orm-cli migrate up -d ${MIGRATION_DIR}

  "mig:revert":
    cmds:
      - docker-compose exec api sea-orm-cli migrate down -d ${MIGRATION_DIR}

  "k6:todo:create":
    cmds:
      - k6 run ${K6_DIR}/todo/create.js

  "k6:todo:list":
    cmds:
      - k6 run ${K6_DIR}/todo/list.js
