name: test

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - client
          - server
          - server/crud
          - server/entity
          - server/migration

  steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cd ${{ matrix.folder }} && cargo fmt -- --check && cargo clippy && cargo test
